// File generated from our OpenAPI spec by Stainless.

package so.prelude.sdk.models

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test
import so.prelude.sdk.core.jsonMapper

internal class VerificationPhoneHistoryRetrieveResponseTest {

    @Test
    fun create() {
        val verificationPhoneHistoryRetrieveResponse =
            VerificationPhoneHistoryRetrieveResponse.builder()
                .id("vrf_01jc0t6fwwfgfsq1md24mhyztj")
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .expiresAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .phoneNumber("+33612345678")
                .status(VerificationPhoneHistoryRetrieveResponse.Status.CONVERTED)
                .appVersion("app_version")
                .addBlockReason(
                    VerificationPhoneHistoryRetrieveResponse.BlockReason.BEHAVIORAL_PATTERN
                )
                .carrier(PhoneVerificationCarrier.builder().mccmnc("208-01").name("Orange").build())
                .correlationId("correlation_id")
                .deviceModel("iPhone15,2")
                .devicePlatform(VerificationPhoneHistoryRetrieveResponse.DevicePlatform.ANDROID)
                .ipAddress("ip_address")
                .ipAddressRegion("FR")
                .ipDistanceMeters(0L)
                .lifecycle(
                    VerificationPhoneHistoryRetrieveResponse.Lifecycle.builder()
                        .addEvent(
                            VerificationPhoneHistoryRetrieveResponse.Lifecycle.Event.builder()
                                .type(
                                    VerificationPhoneHistoryRetrieveResponse.Lifecycle.Event.Type
                                        .CREATE
                                )
                                .attempt(
                                    VerificationPhoneHistoryRetrieveResponse.Lifecycle.Event.Attempt
                                        .builder()
                                        .id("id")
                                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .carrier(
                                            PhoneVerificationCarrier.builder()
                                                .mccmnc("208-01")
                                                .name("Orange")
                                                .build()
                                        )
                                        .channel(
                                            VerificationPhoneHistoryRetrieveResponse.Lifecycle.Event
                                                .Attempt
                                                .Channel
                                                .SMS
                                        )
                                        .content("content")
                                        .cost(
                                            PhoneVerificationMoney.builder()
                                                .amount("0.042")
                                                .currency("EUR")
                                                .build()
                                        )
                                        .addDeliveryEvent(
                                            VerificationPhoneHistoryRetrieveResponse.Lifecycle.Event
                                                .Attempt
                                                .DeliveryEvent
                                                .builder()
                                                .receivedAt(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .status(
                                                    VerificationPhoneHistoryRetrieveResponse
                                                        .Lifecycle
                                                        .Event
                                                        .Attempt
                                                        .DeliveryEvent
                                                        .Status
                                                        .UNKNOWN
                                                )
                                                .build()
                                        )
                                        .deliveryStatus(
                                            VerificationPhoneHistoryRetrieveResponse.Lifecycle.Event
                                                .Attempt
                                                .DeliveryStatus
                                                .UNKNOWN
                                        )
                                        .preferredChannel(
                                            VerificationPhoneHistoryRetrieveResponse.Lifecycle.Event
                                                .Attempt
                                                .PreferredChannel
                                                .SMS
                                        )
                                        .status(
                                            VerificationPhoneHistoryRetrieveResponse.Lifecycle.Event
                                                .Attempt
                                                .Status
                                                .SUCCEEDED
                                        )
                                        .trigger(
                                            VerificationPhoneHistoryRetrieveResponse.Lifecycle.Event
                                                .Attempt
                                                .Trigger
                                                .INITIAL
                                        )
                                        .build()
                                )
                                .check(
                                    VerificationPhoneHistoryRetrieveResponse.Lifecycle.Event.Check
                                        .builder()
                                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .isValid_(true)
                                        .channel(
                                            VerificationPhoneHistoryRetrieveResponse.Lifecycle.Event
                                                .Check
                                                .Channel
                                                .SMS
                                        )
                                        .psd2Info(
                                            VerificationPhoneHistoryRetrieveResponse.Lifecycle.Event
                                                .Check
                                                .Psd2Info
                                                .builder()
                                                .expectedTransaction(
                                                    PhoneVerificationPsd2Transaction.builder()
                                                        .amount(
                                                            PhoneVerificationMoney.builder()
                                                                .amount("0.042")
                                                                .currency("EUR")
                                                                .build()
                                                        )
                                                        .recipient("recipient")
                                                        .build()
                                                )
                                                .receivedTransaction(
                                                    PhoneVerificationPsd2Transaction.builder()
                                                        .amount(
                                                            PhoneVerificationMoney.builder()
                                                                .amount("0.042")
                                                                .currency("EUR")
                                                                .build()
                                                        )
                                                        .recipient("recipient")
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .statusDetail(
                                            VerificationPhoneHistoryRetrieveResponse.Lifecycle.Event
                                                .Check
                                                .StatusDetail
                                                .EXPIRED_ATTEMPT
                                        )
                                        .value("value")
                                        .build()
                                )
                                .create(
                                    VerificationPhoneHistoryRetrieveResponse.Lifecycle.Event.Create
                                        .builder()
                                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .cost(
                                            PhoneVerificationMoney.builder()
                                                .amount("0.042")
                                                .currency("EUR")
                                                .build()
                                        )
                                        .build()
                                )
                                .signals(
                                    VerificationPhoneHistoryRetrieveResponse.Lifecycle.Event.Signals
                                        .builder()
                                        .receivedAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .expiredAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .status(
                                            VerificationPhoneHistoryRetrieveResponse.Lifecycle.Event
                                                .Signals
                                                .Status
                                                .VALID
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .totalCost(
                            PhoneVerificationMoney.builder().amount("0.042").currency("EUR").build()
                        )
                        .undeliverableRouteCount(0L)
                        .build()
                )
                .phoneNumberCondition(
                    VerificationPhoneHistoryRetrieveResponse.PhoneNumberCondition.ALLOW_LISTED
                )
                .phoneNumberCurrentCondition(
                    VerificationPhoneHistoryRetrieveResponse.PhoneNumberCurrentCondition
                        .ALLOW_LISTED
                )
                .phoneNumberRegion("FR")
                .signals(
                    VerificationPhoneHistoryRetrieveResponse.Signals.builder()
                        .isTrustedUser(true)
                        .deviceId("device_id")
                        .ja4Fingerprint("ja4_fingerprint")
                        .osVersion("os_version")
                        .userAgent("user_agent")
                        .build()
                )
                .signalsHashStatus(VerificationPhoneHistoryRetrieveResponse.SignalsHashStatus.VALID)
                .templateId("template_id")
                .build()

        assertThat(verificationPhoneHistoryRetrieveResponse.id())
            .isEqualTo("vrf_01jc0t6fwwfgfsq1md24mhyztj")
        assertThat(verificationPhoneHistoryRetrieveResponse.createdAt())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(verificationPhoneHistoryRetrieveResponse.expiresAt())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(verificationPhoneHistoryRetrieveResponse.phoneNumber()).isEqualTo("+33612345678")
        assertThat(verificationPhoneHistoryRetrieveResponse.status())
            .isEqualTo(VerificationPhoneHistoryRetrieveResponse.Status.CONVERTED)
        assertThat(verificationPhoneHistoryRetrieveResponse.appVersion()).contains("app_version")
        assertThat(verificationPhoneHistoryRetrieveResponse.blockReasons().getOrNull())
            .containsExactly(
                VerificationPhoneHistoryRetrieveResponse.BlockReason.BEHAVIORAL_PATTERN
            )
        assertThat(verificationPhoneHistoryRetrieveResponse.carrier())
            .contains(PhoneVerificationCarrier.builder().mccmnc("208-01").name("Orange").build())
        assertThat(verificationPhoneHistoryRetrieveResponse.correlationId())
            .contains("correlation_id")
        assertThat(verificationPhoneHistoryRetrieveResponse.deviceModel()).contains("iPhone15,2")
        assertThat(verificationPhoneHistoryRetrieveResponse.devicePlatform())
            .contains(VerificationPhoneHistoryRetrieveResponse.DevicePlatform.ANDROID)
        assertThat(verificationPhoneHistoryRetrieveResponse.ipAddress()).contains("ip_address")
        assertThat(verificationPhoneHistoryRetrieveResponse.ipAddressRegion()).contains("FR")
        assertThat(verificationPhoneHistoryRetrieveResponse.ipDistanceMeters()).contains(0L)
        assertThat(verificationPhoneHistoryRetrieveResponse.lifecycle())
            .contains(
                VerificationPhoneHistoryRetrieveResponse.Lifecycle.builder()
                    .addEvent(
                        VerificationPhoneHistoryRetrieveResponse.Lifecycle.Event.builder()
                            .type(
                                VerificationPhoneHistoryRetrieveResponse.Lifecycle.Event.Type.CREATE
                            )
                            .attempt(
                                VerificationPhoneHistoryRetrieveResponse.Lifecycle.Event.Attempt
                                    .builder()
                                    .id("id")
                                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .carrier(
                                        PhoneVerificationCarrier.builder()
                                            .mccmnc("208-01")
                                            .name("Orange")
                                            .build()
                                    )
                                    .channel(
                                        VerificationPhoneHistoryRetrieveResponse.Lifecycle.Event
                                            .Attempt
                                            .Channel
                                            .SMS
                                    )
                                    .content("content")
                                    .cost(
                                        PhoneVerificationMoney.builder()
                                            .amount("0.042")
                                            .currency("EUR")
                                            .build()
                                    )
                                    .addDeliveryEvent(
                                        VerificationPhoneHistoryRetrieveResponse.Lifecycle.Event
                                            .Attempt
                                            .DeliveryEvent
                                            .builder()
                                            .receivedAt(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .status(
                                                VerificationPhoneHistoryRetrieveResponse.Lifecycle
                                                    .Event
                                                    .Attempt
                                                    .DeliveryEvent
                                                    .Status
                                                    .UNKNOWN
                                            )
                                            .build()
                                    )
                                    .deliveryStatus(
                                        VerificationPhoneHistoryRetrieveResponse.Lifecycle.Event
                                            .Attempt
                                            .DeliveryStatus
                                            .UNKNOWN
                                    )
                                    .preferredChannel(
                                        VerificationPhoneHistoryRetrieveResponse.Lifecycle.Event
                                            .Attempt
                                            .PreferredChannel
                                            .SMS
                                    )
                                    .status(
                                        VerificationPhoneHistoryRetrieveResponse.Lifecycle.Event
                                            .Attempt
                                            .Status
                                            .SUCCEEDED
                                    )
                                    .trigger(
                                        VerificationPhoneHistoryRetrieveResponse.Lifecycle.Event
                                            .Attempt
                                            .Trigger
                                            .INITIAL
                                    )
                                    .build()
                            )
                            .check(
                                VerificationPhoneHistoryRetrieveResponse.Lifecycle.Event.Check
                                    .builder()
                                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .isValid_(true)
                                    .channel(
                                        VerificationPhoneHistoryRetrieveResponse.Lifecycle.Event
                                            .Check
                                            .Channel
                                            .SMS
                                    )
                                    .psd2Info(
                                        VerificationPhoneHistoryRetrieveResponse.Lifecycle.Event
                                            .Check
                                            .Psd2Info
                                            .builder()
                                            .expectedTransaction(
                                                PhoneVerificationPsd2Transaction.builder()
                                                    .amount(
                                                        PhoneVerificationMoney.builder()
                                                            .amount("0.042")
                                                            .currency("EUR")
                                                            .build()
                                                    )
                                                    .recipient("recipient")
                                                    .build()
                                            )
                                            .receivedTransaction(
                                                PhoneVerificationPsd2Transaction.builder()
                                                    .amount(
                                                        PhoneVerificationMoney.builder()
                                                            .amount("0.042")
                                                            .currency("EUR")
                                                            .build()
                                                    )
                                                    .recipient("recipient")
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .statusDetail(
                                        VerificationPhoneHistoryRetrieveResponse.Lifecycle.Event
                                            .Check
                                            .StatusDetail
                                            .EXPIRED_ATTEMPT
                                    )
                                    .value("value")
                                    .build()
                            )
                            .create(
                                VerificationPhoneHistoryRetrieveResponse.Lifecycle.Event.Create
                                    .builder()
                                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .cost(
                                        PhoneVerificationMoney.builder()
                                            .amount("0.042")
                                            .currency("EUR")
                                            .build()
                                    )
                                    .build()
                            )
                            .signals(
                                VerificationPhoneHistoryRetrieveResponse.Lifecycle.Event.Signals
                                    .builder()
                                    .receivedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .expiredAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .status(
                                        VerificationPhoneHistoryRetrieveResponse.Lifecycle.Event
                                            .Signals
                                            .Status
                                            .VALID
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .totalCost(
                        PhoneVerificationMoney.builder().amount("0.042").currency("EUR").build()
                    )
                    .undeliverableRouteCount(0L)
                    .build()
            )
        assertThat(verificationPhoneHistoryRetrieveResponse.phoneNumberCondition())
            .contains(VerificationPhoneHistoryRetrieveResponse.PhoneNumberCondition.ALLOW_LISTED)
        assertThat(verificationPhoneHistoryRetrieveResponse.phoneNumberCurrentCondition())
            .contains(
                VerificationPhoneHistoryRetrieveResponse.PhoneNumberCurrentCondition.ALLOW_LISTED
            )
        assertThat(verificationPhoneHistoryRetrieveResponse.phoneNumberRegion()).contains("FR")
        assertThat(verificationPhoneHistoryRetrieveResponse.signals())
            .contains(
                VerificationPhoneHistoryRetrieveResponse.Signals.builder()
                    .isTrustedUser(true)
                    .deviceId("device_id")
                    .ja4Fingerprint("ja4_fingerprint")
                    .osVersion("os_version")
                    .userAgent("user_agent")
                    .build()
            )
        assertThat(verificationPhoneHistoryRetrieveResponse.signalsHashStatus())
            .contains(VerificationPhoneHistoryRetrieveResponse.SignalsHashStatus.VALID)
        assertThat(verificationPhoneHistoryRetrieveResponse.templateId()).contains("template_id")
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val verificationPhoneHistoryRetrieveResponse =
            VerificationPhoneHistoryRetrieveResponse.builder()
                .id("vrf_01jc0t6fwwfgfsq1md24mhyztj")
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .expiresAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .phoneNumber("+33612345678")
                .status(VerificationPhoneHistoryRetrieveResponse.Status.CONVERTED)
                .appVersion("app_version")
                .addBlockReason(
                    VerificationPhoneHistoryRetrieveResponse.BlockReason.BEHAVIORAL_PATTERN
                )
                .carrier(PhoneVerificationCarrier.builder().mccmnc("208-01").name("Orange").build())
                .correlationId("correlation_id")
                .deviceModel("iPhone15,2")
                .devicePlatform(VerificationPhoneHistoryRetrieveResponse.DevicePlatform.ANDROID)
                .ipAddress("ip_address")
                .ipAddressRegion("FR")
                .ipDistanceMeters(0L)
                .lifecycle(
                    VerificationPhoneHistoryRetrieveResponse.Lifecycle.builder()
                        .addEvent(
                            VerificationPhoneHistoryRetrieveResponse.Lifecycle.Event.builder()
                                .type(
                                    VerificationPhoneHistoryRetrieveResponse.Lifecycle.Event.Type
                                        .CREATE
                                )
                                .attempt(
                                    VerificationPhoneHistoryRetrieveResponse.Lifecycle.Event.Attempt
                                        .builder()
                                        .id("id")
                                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .carrier(
                                            PhoneVerificationCarrier.builder()
                                                .mccmnc("208-01")
                                                .name("Orange")
                                                .build()
                                        )
                                        .channel(
                                            VerificationPhoneHistoryRetrieveResponse.Lifecycle.Event
                                                .Attempt
                                                .Channel
                                                .SMS
                                        )
                                        .content("content")
                                        .cost(
                                            PhoneVerificationMoney.builder()
                                                .amount("0.042")
                                                .currency("EUR")
                                                .build()
                                        )
                                        .addDeliveryEvent(
                                            VerificationPhoneHistoryRetrieveResponse.Lifecycle.Event
                                                .Attempt
                                                .DeliveryEvent
                                                .builder()
                                                .receivedAt(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .status(
                                                    VerificationPhoneHistoryRetrieveResponse
                                                        .Lifecycle
                                                        .Event
                                                        .Attempt
                                                        .DeliveryEvent
                                                        .Status
                                                        .UNKNOWN
                                                )
                                                .build()
                                        )
                                        .deliveryStatus(
                                            VerificationPhoneHistoryRetrieveResponse.Lifecycle.Event
                                                .Attempt
                                                .DeliveryStatus
                                                .UNKNOWN
                                        )
                                        .preferredChannel(
                                            VerificationPhoneHistoryRetrieveResponse.Lifecycle.Event
                                                .Attempt
                                                .PreferredChannel
                                                .SMS
                                        )
                                        .status(
                                            VerificationPhoneHistoryRetrieveResponse.Lifecycle.Event
                                                .Attempt
                                                .Status
                                                .SUCCEEDED
                                        )
                                        .trigger(
                                            VerificationPhoneHistoryRetrieveResponse.Lifecycle.Event
                                                .Attempt
                                                .Trigger
                                                .INITIAL
                                        )
                                        .build()
                                )
                                .check(
                                    VerificationPhoneHistoryRetrieveResponse.Lifecycle.Event.Check
                                        .builder()
                                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .isValid_(true)
                                        .channel(
                                            VerificationPhoneHistoryRetrieveResponse.Lifecycle.Event
                                                .Check
                                                .Channel
                                                .SMS
                                        )
                                        .psd2Info(
                                            VerificationPhoneHistoryRetrieveResponse.Lifecycle.Event
                                                .Check
                                                .Psd2Info
                                                .builder()
                                                .expectedTransaction(
                                                    PhoneVerificationPsd2Transaction.builder()
                                                        .amount(
                                                            PhoneVerificationMoney.builder()
                                                                .amount("0.042")
                                                                .currency("EUR")
                                                                .build()
                                                        )
                                                        .recipient("recipient")
                                                        .build()
                                                )
                                                .receivedTransaction(
                                                    PhoneVerificationPsd2Transaction.builder()
                                                        .amount(
                                                            PhoneVerificationMoney.builder()
                                                                .amount("0.042")
                                                                .currency("EUR")
                                                                .build()
                                                        )
                                                        .recipient("recipient")
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .statusDetail(
                                            VerificationPhoneHistoryRetrieveResponse.Lifecycle.Event
                                                .Check
                                                .StatusDetail
                                                .EXPIRED_ATTEMPT
                                        )
                                        .value("value")
                                        .build()
                                )
                                .create(
                                    VerificationPhoneHistoryRetrieveResponse.Lifecycle.Event.Create
                                        .builder()
                                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .cost(
                                            PhoneVerificationMoney.builder()
                                                .amount("0.042")
                                                .currency("EUR")
                                                .build()
                                        )
                                        .build()
                                )
                                .signals(
                                    VerificationPhoneHistoryRetrieveResponse.Lifecycle.Event.Signals
                                        .builder()
                                        .receivedAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .expiredAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .status(
                                            VerificationPhoneHistoryRetrieveResponse.Lifecycle.Event
                                                .Signals
                                                .Status
                                                .VALID
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .totalCost(
                            PhoneVerificationMoney.builder().amount("0.042").currency("EUR").build()
                        )
                        .undeliverableRouteCount(0L)
                        .build()
                )
                .phoneNumberCondition(
                    VerificationPhoneHistoryRetrieveResponse.PhoneNumberCondition.ALLOW_LISTED
                )
                .phoneNumberCurrentCondition(
                    VerificationPhoneHistoryRetrieveResponse.PhoneNumberCurrentCondition
                        .ALLOW_LISTED
                )
                .phoneNumberRegion("FR")
                .signals(
                    VerificationPhoneHistoryRetrieveResponse.Signals.builder()
                        .isTrustedUser(true)
                        .deviceId("device_id")
                        .ja4Fingerprint("ja4_fingerprint")
                        .osVersion("os_version")
                        .userAgent("user_agent")
                        .build()
                )
                .signalsHashStatus(VerificationPhoneHistoryRetrieveResponse.SignalsHashStatus.VALID)
                .templateId("template_id")
                .build()

        val roundtrippedVerificationPhoneHistoryRetrieveResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(verificationPhoneHistoryRetrieveResponse),
                jacksonTypeRef<VerificationPhoneHistoryRetrieveResponse>(),
            )

        assertThat(roundtrippedVerificationPhoneHistoryRetrieveResponse)
            .isEqualTo(verificationPhoneHistoryRetrieveResponse)
    }
}
